"""posts table

Revision ID: 68abf5a44be5
Revises: 404fa602410e
Create Date: 2018-12-20 20:35:01.215213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68abf5a44be5'
down_revision = '404fa602410e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_timestamp'), 'person', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_timestamp'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
